# Generated by Django 5.2.8 on 2026-01-10 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0002_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='first_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hr_management.employee'),
        ),
    ]
